# Generated by Django 4.0.4 on 2022-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0002_postre_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empanada',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='postre',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
