# Generated by Django 4.0.4 on 2022-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0003_alter_bebida_nombre_alter_empanada_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
    ]
