# Generated by Django 4.0.4 on 2022-07-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0004_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='foto',
        ),
    ]
