# Generated by Django 4.0.4 on 2022-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0006_alter_pizza_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas'),
        ),
        migrations.AddField(
            model_name='empanada',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empanadas'),
        ),
        migrations.AddField(
            model_name='postre',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='postres'),
        ),
    ]
