# Generated by Django 4.0.4 on 2022-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0007_bebida_foto_empanada_foto_postre_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portadas')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
