# Generated by Django 4.0.4 on 2022-07-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_web', '0008_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='secundaria_portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portadas')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
